import { TProductType } from "@/types/types";

export const navLinks: string[] = ["Home", "Products", "Cart"];
export const navButtons: string[] = ["Login", "Register"];
export const productItems: TProductType[] = [
	{
		ProductId: 0,
		ProductImage: "Product Image",
		ProductName: "Product One",
		ProductPrice: 149.99,
		ProductSlug: "Product Slug",
		ProductDescription: "This is the product's description",
		ProductQuantityInStock: 2,
		CategoryId: 0,
		CreatedAt: new Date(),
	},
	{
		ProductId: 1,
		ProductImage: "Product Image",
		ProductName: "Product Two",
		ProductPrice: 349.99,
		ProductSlug: "Product Slug",
		ProductDescription: "This is the product's description",
		ProductQuantityInStock: 2,
		CategoryId: 1,
		CreatedAt: new Date(),
	},
	{
		ProductId: 2,
		ProductImage: "Product Image",
		ProductName: "Product Three",
		ProductPrice: 249.99,
		ProductSlug: "Product Slug",
		ProductDescription: "This is the product's description",
		ProductQuantityInStock: 2,
		CategoryId: 2,
		CreatedAt: new Date(),
	},
	{
		ProductId: 3,
		ProductImage: "Product Image",
		ProductName: "Product Four",
		ProductPrice: 749.99,
		ProductSlug: "Product Slug",
		ProductDescription: "This is the product's description",
		ProductQuantityInStock: 2,
		CategoryId: 3,
		CreatedAt: new Date(),
	},
	{
		ProductId: 4,
		ProductImage: "Product Image",
		ProductName: "Product Five",
		ProductPrice: 999.99,
		ProductSlug: "Product Slug",
		ProductDescription: "This is the product's description",
		ProductQuantityInStock: 2,
		CategoryId: 4,
		CreatedAt: new Date(),
	},
	{
		ProductId: 5,
		ProductImage: "Product Image",
		ProductName: "Product Six",
		ProductPrice: 49.99,
		ProductSlug: "Product Slug",
		ProductDescription: "This is the product's description",
		ProductQuantityInStock: 2,
		CategoryId: 5,
		CreatedAt: new Date(),
	},
];
