export const navLinks: string[] = ["Home", "Products", "Cart"];
export const navButtons: string[] = ["Login", "Register"];
export const productItems: any[] = [
	{
		ProductId: 0,
		ProductImage: "Product Image",
		ProductName: "Product Name",
		ProductPrice: 199.99,
		ProductSlug: "Product Slug",
		ProductDescription: "This is the product's description",
		ProductQuantityInStock: 2,
		CategoryId: 0,
		CreatedAt: new Date(),
	},
	{
		ProductId: 1,
		ProductImage: "Product Image",
		ProductName: "Product Name",
		ProductPrice: 199.99,
		ProductSlug: "Product Slug",
		ProductDescription: "This is the product's description",
		ProductQuantityInStock: 2,
		CategoryId: 1,
		CreatedAt: new Date(),
	},
	{
		ProductId: 2,
		ProductImage: "Product Image",
		ProductName: "Product Name",
		ProductPrice: 199.99,
		ProductSlug: "Product Slug",
		ProductDescription: "This is the product's description",
		ProductQuantityInStock: 2,
		CategoryId: 2,
		CreatedAt: new Date(),
	},
	{
		ProductId: 3,
		ProductImage: "Product Image",
		ProductName: "Product Name",
		ProductPrice: 199.99,
		ProductSlug: "Product Slug",
		ProductDescription: "This is the product's description",
		ProductQuantityInStock: 2,
		CategoryId: 3,
		CreatedAt: new Date(),
	},
	{
		ProductId: 4,
		ProductImage: "Product Image",
		ProductName: "Product Name",
		ProductPrice: 199.99,
		ProductSlug: "Product Slug",
		ProductDescription: "This is the product's description",
		ProductQuantityInStock: 2,
		CategoryId: 4,
		CreatedAt: new Date(),
	},
	{
		ProductId: 5,
		ProductImage: "Product Image",
		ProductName: "Product Name",
		ProductPrice: 199.99,
		ProductSlug: "Product Slug",
		ProductDescription: "This is the product's description",
		ProductQuantityInStock: 2,
		CategoryId: 5,
		CreatedAt: new Date(),
	},
];

export const cartItems: any[] = [
	{
		id: 0,
		name: "Product Name",
		price: "$199.99",
		total: "$199.99",
	},
	{
		id: 1,
		name: "Product Name",
		price: "$199.99",
		total: "$199.99",
	},
	{
		id: 2,
		name: "Product Name",
		price: "$199.99",
		total: "$199.99",
	},
	{
		id: 3,
		name: "Product Name",
		price: "$199.99",
		total: "$199.99",
	},
	{
		id: 4,
		name: "Product Name",
		price: "$199.99",
		total: "$199.99",
	},
	{
		id: 5,
		name: "Product Name",
		price: "$199.99",
		total: "$199.99",
	},
	{
		id: 6,
		name: "Product Name",
		price: "$199.99",
		total: "$199.99",
	},
];
